#!/usr/bin/env bash
# Configure custom host resolution for localhost and facebook.com

# Overwrite /etc/hosts with required values
echo "127.0.0.2 localhost" | sudo tee /etc/hosts > /dev/null
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null
