#!/usr/bin/env bash
# This script updates /etc/hosts so localhost resolves to 127.0.0.2 and facebook.com to 8.8.8.8

sudo sed -i s/^127.0.0.1s+localhost/127.0.0.2 localhost/ /etc/hosts

# remove any previous facebook.com entries
sudo sed -i /facebook.com/d /etc/hosts

# add new line
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts >/dev/null
